# Generated by Django 2.1.3 on 2018-11-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='zipcode',
            field=models.IntegerField(verbose_name='zip code'),
        ),
    ]
