# Generated by Django 2.1.3 on 2018-11-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_auto_20181129_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('start_use', models.DateTimeField(verbose_name='date started using')),
                ('end_use', models.DateTimeField(verbose_name='date ended using')),
                ('main_amps', models.IntegerField(verbose_name='main breaker amps')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=180, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=180, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='panel',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.Building'),
        ),
    ]
