# Generated by Django 2.1.3 on 2018-11-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0003_auto_20181129_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=24)),
                ('start_use', models.DateTimeField(blank=True, verbose_name='date started using')),
                ('end_use', models.DateTimeField(blank=True, verbose_name='date ended using')),
            ],
        ),
        migrations.CreateModel(
            name='Breaker_Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, verbose_name='amps')),
            ],
        ),
        migrations.CreateModel(
            name='Breaker_Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Breaker_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='end_use',
            field=models.DateTimeField(blank=True, verbose_name='date ended using'),
        ),
        migrations.AlterField(
            model_name='building',
            name='start_use',
            field=models.DateTimeField(blank=True, verbose_name='date started using'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Building'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='end_use',
            field=models.DateTimeField(blank=True, verbose_name='date ended using'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='start_use',
            field=models.DateTimeField(blank=True, verbose_name='date started using'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='capacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Breaker_Capacity'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='orientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Breaker_Orientation'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Panel'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Breaker_Position'),
        ),
    ]
