# Generated by Django 2.1.3 on 2018-11-30 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0004_auto_20181129_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker_Poles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poles', models.IntegerField(unique=True, verbose_name='single or double')),
            ],
        ),
        migrations.AddField(
            model_name='breaker',
            name='afci',
            field=models.BooleanField(default=False, verbose_name='is AFCI?'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='gfci',
            field=models.BooleanField(default=False, verbose_name='is GFCI?'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='paired_breaker',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='panel',
            name='brand_model',
            field=models.CharField(blank=True, max_length=36, verbose_name='brand and model'),
        ),
        migrations.AddField(
            model_name='breaker',
            name='poles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Breaker_Poles'),
        ),
    ]
