# Generated by Django 2.1.3 on 2018-11-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0005_auto_20181129_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('start_use', models.DateTimeField(blank=True, verbose_name='date started using')),
                ('end_use', models.DateTimeField(blank=True, verbose_name='date ended using')),
                ('gfci', models.BooleanField(default=False, verbose_name='is GFCI?')),
                ('afci', models.BooleanField(default=False, verbose_name='is AFCI?')),
                ('breaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Breaker')),
            ],
        ),
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Building')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Room'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuits.Device_Type'),
        ),
    ]
